### ISSUE TITLE
NullReferenceException in JsBridge.cs

### ISSUE THREAD

**Issue by brettnagy** [cdeutsch/JsBridge#1]
Hi,

when I run your example project in the iPhone 5.1 simulator with MonoTouch, I get a null reference exception in JsBridge, line 269. Stepping in via the debugger, I can see "Client" is null.

I'm running:

MonoDevelop 3.0.3.2
Monotouch: 5.2.12
Mono 2.10.9 (tarball)
Xcode 4.3.2 (1177)
Mac OS X 10.7.4

Any ideas?

Thanks

**Comment by brettnagy** [comment]
Ok, I just re-read your readme and I see I'm needing a newer version of MonoTouch. I guess the date you list (2010) should really be 2012?

Doh.

**Comment by cdeutsch** [comment]
Yep, you need 5.3.3 and yes indeed that'a a typo, good catch!
http://docs.xamarin.com/ios/releases/MonoTouch_5/MonoTouch_5.3#MonoTouch_5.3.3
